### PR TITLE
CA03 - admin can get the specific item paga; admin can create or edit an item; admin can delete an item

### PR DESCRIPTION
**Pull request by AdrieneTZ**
**add feature:**
- admin can get the specific item paga
- admin can create an item
- admin can edit an item
- admin can delete an item

**add dependencies:**
- assert: easily operate if condition and send error message

**require module**
- sequelize operator

**resolve conflict**

### CODE REVIEW

**Review by wuwachon — COMMENTED** [review]
- getItem：
I think data also need type of category and level of game

- postItem：
1. await Item.create and res.status(201).json({ status: 'success' })
    can be dropped out of if (isPublished) { ... }
2. should add "assert(name || isLegal , 'some field are required for publishing.')" as putItem below?
 
- putItem：
1. assert(name || isLegal || description || law, 'All field are required for publishing.')
    if the isLegal is true, no need the description and law attribute.
2. await Item.update and res.status(200).json({ status: 'success' })
    can be dropped out of if (isPublished) { ... }

- about the gameId...
we need to discuss about all the name of tables and their attributes names

**Comment by AdrieneTZ** [comment]
**getItem:**
- add category name and game level in targetItem

**postItem & putItem:**
- if item is not legal, before publishing, check description && law fields are not empty
- modify create & update process

**deleteItem:**
- if the item is the last legal one in the game level, that item can't be deleted

**Comment by AdrieneTZ** [comment]
**deleteItem:**
- fix logic of finding level item

**Review by wuwachon — APPROVED** [review]
all good!

**Pull request merged**
